---
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name : "default"
    strategies:
      "HighNodeUtilization":
        enabled: true
        params:
          thresholds:
            "memory": 20
