---
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name : "default"
    strategies:
      "PodLifeTime":
        enabled: true
        params:
          maxPodLifeTimeSeconds: 604800 # 7 days
