apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "LowNodeUtilization":
     enabled: true
     params:
       thresholds:
         "cpu" : 20
         "memory": 20
         "pods": 20
       targetThresholds:
         "cpu" : 50
         "memory": 50
         "pods": 50
  "RemovePodsHavingTooManyRestarts":
     enabled: true
     params:
       podRestartThreshold: 100
       includingInitContainers: true
